"""Add Review Model

Revision ID: 33d8f46814e1
Revises: d4e60fc3b7f1
Create Date: 2023-10-10 13:30:56.790196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d8f46814e1'
down_revision = 'd4e60fc3b7f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
