"""Add Review Model

Revision ID: 675d97e1c69f
Revises: 9276f7f25f79
Create Date: 2023-10-10 13:34:43.957631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675d97e1c69f'
down_revision = '9276f7f25f79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
