"""Create Game Model

Revision ID: 9276f7f25f79
Revises: 33d8f46814e1
Create Date: 2023-10-10 13:32:10.645352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9276f7f25f79'
down_revision = '33d8f46814e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
